### ISSUE TITLE
Release of new version failing

### ISSUE THREAD

**Issue by grossir** [freelawproject/juriscraper#1308]
I was trying to release a new juriscraper version, and the deploy action has an [error](https://github.com/freelawproject/juriscraper/actions/runs/12931944569/job/36067141744)
```
Checking dist/juriscraper-2.6.53-py27-none-any.whl: ERROR    InvalidDistribution: Invalid distribution metadata: unrecognized or    
         malformed field 'license-file'
```
This has been reported by other people here https://github.com/pypa/twine/issues/1216#issuecomment-2609745412 and the solution seems to be using specific versions of `twine` and `packaging` packages

**Comment by grossir** [comment]
just setting the versions in requirements.txt did not work
```
twine>=6.1
packaging==24.2

# tried this too
twine>=6.1
packaging>=24.2
```

It seems that the packaging requirement is not met; From the [actions](https://github.com/freelawproject/juriscraper/actions/runs/12940460624/job/36094725096) log
```
Requirement already satisfied: packaging>=24.0 in /usr/lib/python3/dist-packages (from twine) (24.0)
```

**Comment by grossir** [comment]
From the cited twine issue, I tried updating the `requirements.txt` file, and that failed. 
After reading some more, this is because there are 2 distinct steps in the process of building:
- setting up the build environment
- actually building the package

the requirements.txt file belongs to the second step; but we actually needed to update the `packaging` version in the first step. This was solved by adding a `-run` step to the pypi workflow. We will need to do the same for other FLP repos that use the same workflow

```
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: python -m pip install -U packaging
      - uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.pypi_token }}
          build: true

```
