### ISSUE TITLE
Optimize/Configure Circle CI and Rip out Travis

### ISSUE THREAD

**Issue by arderyp** [freelawproject/juriscraper#252]
Looks like we are abandoning Travis and moving to Circle (see #251).  The basic Circle CI config is set up, but none of the bells and whistles are configured.  That's what this issue is about.  Thing to configure:

- cache dependencies between runs, stores results
- push new versions to pypi
- post to Slack
- send email build notices (?)

[Circle CI configuration documentation](https://circleci.com/docs/2.0/configuration-reference/)

**Comment by mlissner** [comment]
Yeah, that line is fine. I think we're doing private key encryption there, but we'll want to rip out that whole file before we're done here. Changing title to cover nixing old Travis junk too.

**Comment by mlissner** [comment]
Here's the Travis config that I'm about to nuke:

```yml
sudo: false
language: python
python:
- '2.7'
script: python setup.py test
install: pip install -U setuptools ; pip install .
cache: pip
notifications:
  slack: flp-talk:iG0Qd1lAUJuXZlkcf2sbUC5P
deploy:
  provider: pypi
  distributions: bdist_wheel
  user: freelawproject
  password:
    secure: gI70+niTaZicDALei/ewdSgL13oSYyiQ9tS2eMH7OpjDQ5FSJdPzghNKm2v+GwC2l4T74I0+hZEWx15fNAXxDLYCCEbIikgZ7ELro3gwKKtTYXfo3QD0Z/COJ6hbit3NiLgJRiag7IGo/AUBCABat88PmbIJB4qgUrv0/FEvbeM=
  on:
    tags: true
```
